name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: jrlagrone/github-profile-3d-contrib@v0.8.0
        env:
          GITHUB_TOKEN: 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
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
